-- ============================================================
-- Migración: separar ÁREAS (organigrama) de USUARIOS
-- Se migra SOLO al usuario Director General (todos los permisos)
-- ============================================================

-- 1) Nueva tabla areas (organigrama jerárquico independiente)
CREATE TABLE IF NOT EXISTS areas (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(255) NOT NULL UNIQUE,
    nivel     VARCHAR(30)  NOT NULL,
    parent_id BIGINT,
    activo    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT areas_nivel_check CHECK (nivel IN (
        'DEPARTAMENTO','COORDINACION','DIRECCION','DIRECCION_GENERAL'))
);

-- 2) Columnas nuevas en usuarios
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS area_id BIGINT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS password_expirada BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS fecha_expiracion_password TIMESTAMP;

-- 3) Columnas nuevas en requisiciones (cadena jerárquica por ÁREA)
ALTER TABLE requisiciones ADD COLUMN IF NOT EXISTS area_id BIGINT;
ALTER TABLE requisiciones ADD COLUMN IF NOT EXISTS coord_area_id BIGINT;
ALTER TABLE requisiciones ADD COLUMN IF NOT EXISTS dir_area_id BIGINT;
ALTER TABLE requisiciones ADD COLUMN IF NOT EXISTS dir_gral_area_id BIGINT;

-- 4) Crear el área raíz "Dirección General" (raíz del organigrama)
INSERT INTO areas (nombre, nivel, parent_id, activo)
VALUES ('Dirección General', 'DIRECCION_GENERAL', NULL, TRUE)
ON CONFLICT (nombre) DO NOTHING;

-- 5) Migrar el usuario Director General:
--    - se le asigna al área raíz
--    - queda activo, con su rol (todos los permisos) y sin expiración de contraseña
UPDATE usuarios
SET area_id = (SELECT id FROM areas WHERE nombre = 'Dirección General'),
    activo = TRUE,
    password_expirada = FALSE
WHERE username = 'dirgeneral';

-- 6) Relación usuarios -> areas (FK)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuarios_area') THEN
        ALTER TABLE usuarios
            ADD CONSTRAINT fk_usuarios_area FOREIGN KEY (area_id) REFERENCES areas (id);
    END IF;
END $$;