-- =========================================================
-- Esquema del Sistema de Requerimientos
-- Compatible con las entidades JPA (spring.jpa.hibernate.ddl-auto=update
-- no volverá a alterar nada porque esta DDL coincide).
-- Pégalo completo en el SQL editor de Neon (rama "production").
-- =========================================================

-- Áreas del organigrama
CREATE TABLE areas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255) NOT NULL,
    nivel       VARCHAR(30)  NOT NULL,
    parent_id   BIGINT,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT areas_nombre_key UNIQUE (nombre),
    CONSTRAINT areas_nivel_check CHECK (nivel IN ('DEPARTAMENTO','COORDINACION','DIRECCION','DIRECCION_GENERAL'))
);

-- Usuarios del sistema
CREATE TABLE usuarios (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                  VARCHAR(50)  NOT NULL,
    password                  VARCHAR(255) NOT NULL,
    nombre_completo           VARCHAR(255) NOT NULL,
    rol                       VARCHAR(40)  NOT NULL,
    area_id                   BIGINT,
    password_expirada         BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_expiracion_password TIMESTAMP,
    activo                    BOOLEAN      NOT NULL,
    CONSTRAINT usuarios_username_key UNIQUE (username),
    CONSTRAINT usuarios_rol_check CHECK (rol IN ('ROLE_DEPARTAMENTO','ROLE_COORDINACION','ROLE_DIRECCION','ROLE_DIRECCION_GENERAL','ROLE_MATERIALES')),
    CONSTRAINT fk_usuarios_area FOREIGN KEY (area_id) REFERENCES areas(id)
);

-- Requisiciones de compra
CREATE TABLE requisiciones (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio                 VARCHAR(20)   NOT NULL,
    nombre_solicitante    VARCHAR(255)  NOT NULL,
    area                  VARCHAR(255)  NOT NULL,
    fecha_requerida       VARCHAR(255),
    fecha_solicitud       VARCHAR(255),
    partida_codigo        VARCHAR(255),
    partida_nombre        VARCHAR(255),
    material              VARCHAR(255)  NOT NULL,
    cantidad              DOUBLE PRECISION,
    unidad                VARCHAR(255),
    precio_estimado       DOUBLE PRECISION,
    descripcion           VARCHAR(255),
    justificacion         VARCHAR(255),
    estado_coord          VARCHAR(20),
    estado_dir            VARCHAR(20),
    estado_dir_gral       VARCHAR(20),
    justificacion_rechazo VARCHAR(1000),
    creado_por_id         BIGINT         NOT NULL,
    area_id               BIGINT,
    coord_area_id         BIGINT,
    dir_area_id           BIGINT,
    dir_gral_area_id      BIGINT,
    modificado_por        VARCHAR(255),
    estado_materiales     VARCHAR(20),
    mes_compra            VARCHAR(7),
    proveedor             VARCHAR(200),
    estado_compra         VARCHAR(20),
    tipo_costo            VARCHAR(20),
    precio_compra         DOUBLE PRECISION,
    marca_seleccionada    VARCHAR(200),
    CONSTRAINT requisiciones_folio_key UNIQUE (folio),
    CONSTRAINT requisiciones_estado_coord_check      CHECK (estado_coord      IN ('PENDIENTE','APROBADO','RECHAZADO','NO_APLICA')),
    CONSTRAINT requisiciones_estado_dir_check        CHECK (estado_dir        IN ('PENDIENTE','APROBADO','RECHAZADO','NO_APLICA')),
    CONSTRAINT requisiciones_estado_dir_gral_check   CHECK (estado_dir_gral   IN ('PENDIENTE','APROBADO','RECHAZADO','NO_APLICA')),
    CONSTRAINT requisiciones_estado_materiales_check CHECK (estado_materiales IN ('PENDIENTE','APROBADO','RECHAZADO','NO_APLICA')),
    CONSTRAINT requisiciones_estado_compra_check     CHECK (estado_compra     IN ('EN_COMPRA','COMPRADO','ENTREGADO'))
);

-- Sugerencias (cotizaciones/seguimiento adjuntos a cada requisición)
CREATE TABLE sugerencias (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca              VARCHAR(255),
    modelo             VARCHAR(255),
    precio_estimado    DOUBLE PRECISION,
    enlace_url         VARCHAR(1000),
    archivo_pdf_nombre VARCHAR(255),
    archivo_pdf_url    VARCHAR(1000),
    requisicion_id     BIGINT,
    CONSTRAINT fk_sugerencia_requisicion FOREIGN KEY (requisicion_id) REFERENCES requisiciones(id)
);

-- Bitácora de eventos (aprobaciones, cambios de mes, decisión de costo, etc.)
CREATE TABLE historico_eventos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisicion_id  BIGINT          NOT NULL,
    usuario         VARCHAR(255)    NOT NULL,
    rol             VARCHAR(255)    NOT NULL,
    accion          VARCHAR(255)    NOT NULL,
    campo           VARCHAR(255),
    valor_anterior  VARCHAR(1000),
    valor_nuevo     VARCHAR(1000),
    fecha_hora      TIMESTAMP       NOT NULL
);

-- Catálogo: unidades de medida
CREATE TABLE unidades_medida (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    codigo VARCHAR(10) NOT NULL,
    CONSTRAINT unidades_medida_nombre_key UNIQUE (nombre),
    CONSTRAINT unidades_medida_codigo_key UNIQUE (codigo)
);

-- Catálogo: partidas de gasto
CREATE TABLE partidas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(10)   NOT NULL,
    nombre      VARCHAR(255)  NOT NULL,
    descripcion TEXT          NOT NULL,
    CONSTRAINT partidas_codigo_key UNIQUE (codigo)
);